[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:caddy]
command=/usr/bin/caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
user=root
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/caddy/caddy.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=1

[program:caddy-ui]
command=node_modules/.bin/next dev -H 0.0.0.0 -p 3000
directory=/app
user=caddy-ui
autostart=true
autorestart=true
startsecs=5
environment=NODE_ENV="development",CADDYFILE_PATH="/etc/caddy/Caddyfile"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
